import './App.css';

function App() {
  const adjectives = ["	Addled	"	,
  "	Artless	"	,
  "	Base	"	,
  "	Barren	"	,
  "	Bed-wetting	"	,
  "	Bedraggled	"	,
  "	Bedridden	"	,
  "	Bloated	"	,
  "	Blubbering	"	,
  "	Boisterous	"	,
  "	Boorish	"	,
  "	Bootlicking	"	,
  "	Bottom-feeding	"	,
  "	Brazen	"	,
  "	Brittle	"	,
  "	Bulbous	"	,
  "	Bumbling	"	,
  "	cancerous	"	,
  "	Clenched	"	,
  "	Coarse	"	,
  "	Common	"	,
  "	contemptuous	"	,
  "	Cowardly	"	,
  "	craven	"	,
  "	cretinous	"	,
  "	Crooked	"	,
  "	Crossed eyed	"	,
  "	Cumbersome	"	,
  "	currish	"	,
  "	Cursed	"	,
  "	Cutthroat	"	,
  "	Debauched	"	,
  "	Degenerate	"	,
  "	demon-sired	"	,
  "	demonic	"	,
  "	Dimwitted	"	,
  "	dirt-eating	"	,
  "	Dirty	"	,
  "	Disingenuous	"	,
  "	dismal	"	,
  "	doddering	"	,
  "	dog-headed	"	,
  "	Downtrodden	"	,
  "	Dull	"	,
  "	dunderheaded	"	,
  "	dung-eating	"	,
  "	Errant	"	,
  "	fatherless	"	,
  "	Feral	"	,
  "	Fickle	"	,
  "	fiendish	"	,
  "	Filthy	"	,
  "	flea-bitten	"	,
  "	foolish	"	,
  "	foot-licking	"	,
  "	Forgettable	"	,
  "	Foul	"	,
  "	Frail	"	,
  "	Glaring	"	,
  "	gluttonous	"	,
  "	Grotesque	"	,
  "	Gruesome	"	,
  "	Hapless	"	,
  "	hell-spawned	"	,
  "	hideous	"	,
  "	homely	"	,
  "	Honor-less	"	,
  "	Humorless	"	,
  "	idiotic	"	,
  "	idolatrous	"	,
  "	ill-bred	"	,
  "	Ill-conceived	"	,
  "	ill-fated	"	,
  "	Ill-mannered	"	,
  "	ill-natured	"	,
  "	ill-nurtured	"	,
  "	Immoral	"	,
  "	impertinent	"	,
  "	incestuous	"	,
  "	Inept	"	,
  "	Infectious	"	,
  "	Infernal	"	,
  "	Infested	"	,
  "	inhuman	"	,
  "	Insignificant	"	,
  "	landless	"	,
  "	lice-covered	"	,
  "	lice-infested	"	,
  "	lickspittal	"	,
  "	Lifeless	"	,
  "	Lily-livered	"	,
  "	Loathsome	"	,
  "	Loud	"	,
  "	loutish	"	,
  "	low-born	"	,
  "	Lowly	"	,
  "	lumpish	"	,
  "	Malformed	"	,
  "	Mangled	"	,
  "	Mannerless	"	,
  "	measly	"	,
  "	Mewling	"	,
  "	Misbegotten	"	,
  "	Miserable	"	,
  "	Mongrel	"	,
  "	monstrous	"	,
  "	mouse-hearted	"	,
  "	Muck-suckling	"	,
  "	Musty	"	,
  "	Mute	"	,
  "	Myopic	"	,
  "	namby-pamby	"	,
  "	Near-sighted	"	,
  "	Ninny headed	"	,
  "	Obtuse	"	,
  "	Odiferous	"	,
  "	Ofiesh	"	,
  "	Overblown	"	,
  "	ox-bottomed	"	,
  "	Paltry	"	,
  "	Pathetic	"	,
  "	Petulant	"	,
  "	Pickled	"	,
  "	Pitiful	"	,
  "	Ploughed	"	,
  "	Poisonous	"	,
  "	Pompous	"	,
  "	poor-born	"	,
  "	pox-marked	"	,
  "	poxridden	"	,
  "	preposterous	"	,
  "	Prideful	"	,
  "	Puckered	"	,
  "	puny	"	,
  "	Puss-filled	"	,
  "	Putrid	"	,
  "	Rabid	"	,
  "	Rank	"	,
  "	Raucous	"	,
  "	roguish	"	,
  "	Rotted	"	,
  "	Rotten	"	,
  "	Rough-shod	"	,
  "	Rough-spun	"	,
  "	rude	"	,
  "	Rumbling	"	,
  "	Savage	"	,
  "	scabrous	"	,
  "	Senile	"	,
  "	serpent-sired"	,
  "	shameful	"	,
  "	sheep-biting	"	,
  "	Short-sighted	"	,
  "	Sickly	"	,
  "	simpering	"	,
  "	Simple	"	,
  "	Slobbering	"	,
  "	Slow	"	,
  "	Snaggel-tooth	"	,
  "	Sniveling	"	,
  "	Soaked	"	,
  "	Sodded	"	,
  "	Soiled	"	,
  "	son of a	"	,
  "	Sooted	"	,
  "	Soulless	"	,
  "	Sour	"	,
  "	Spineless	"	,
  "	spittle-dripping	"	,
  "	Spoiled	"	,
  "	Stiff	"	,
  "	sulphurous	"	,
  "	Tempestuous	"	,
  "	Thumb-sucking	"	,
  "	Toothless	"	,
  "	Tottering	"	,
  "	Treacherous	"	,
  "	Treasonous	"	,
  "	Trivial	"	,
  "	Uncivilized	"	,
  "	Uncouth	"	,
  "	Uncultivated	"	,
  "	Uncultured	"	,
  "	Uneducated	"	,
  "	Unkempt	"	,
  "	unmuzzled	"	,
  "	Unrefined	"	,
  "	unworthy	"	,
  "	Vain	"	,
  "	venomous	"	,
  "	vile	"	,
  "	Vulgar	"	,
  "	Wayward	"	,
  "	Weak	"	,
  "	Weak willed	"	,
  "	Withered	"	,
  "	Witless	"	,
  "	woebegone	"	,
  "	Worthless	"	,
  "	wretched	",
  "	sullen	"	,
  "	soggy	"	,
  "	waste of a	"	,
  "	plague-stricken	"	,
  "	meandering	"	,
  "	pompous	"	,
  "	mouth-breathing	"	,
  "	paunchy	"	,
  "	flat-footed	"	,
  "	floundering	"]

  const nouns = ["	ankle-biter	"	,
  "	Buffoon	"	,
  "	bed-wetter	"	,
  "	blaggard	"	,
  "	Blight	"	,
  "	Bloat	"	,
  "	Boar	"	,
  "	Boil	"	,
  "	Braggart	"	,
  "	Cad	"	,
  "	Carnival creature	"	,
  "	Chamber pot	"	,
  "	charlatan	"	,
  "	Clown	"	,
  "	Cod	"	,
  "	Codpiece	"	,
  "	coward	"	,
  "	criminal	"	,
  "	crone	"	,
  "	cur	"	,
  "	Curd	"	,
  "	Cutpurse	"	,
  "	Dandy	"	,
  "	Degenerate	"	,
  "	Disease	"	,
  "	Dolt	"	,
  "	Drain spout	"	,
  "	Dunce	"	,
  "	Dunderhead	"	,
  "	Farce	"	,
  "	Filth	"	,
  "	Floatsam	"	,
  "	Foe	"	,
  "	Fool	"	,
  "	Fraud	"	,
  "	Gnoll	"	,
  "	Goon	"	,
  "	Grime	"	,
  "	guttersnipe	"	,
  "	Heathen	"	,
  "	Hog	"	,
  "	Hooligan	"	,
  "	Ignoramus	"	,
  "	Ill-omen	"	,
  "	imbecile	"	,
  "	Jackal	"	,
  "	jester	"	,
  "	knave	"	,
  "	Leech	"	,
  "	Lickspittle	"	,
  "	Loaf	"	,
  "	Louse	"	,
  "	Lout	"	,
  "	malcontent	"	,
  "	milk drinker	"	,
  "	milksop	"	,
  "	Minnow	"	,
  "	Miscreant	"	,
  "	mongrel	"	,
  "	Muck	"	,
  "	ne’er-do-well	"	,
  "	Nincompoop	"	,
  "	Ninny	"	,
  "	Oaf	"	,
  "	Oathbreaker	"	,
  "	Pansy	"	,
  "	Parasite	"	,
  "	Plague	"	,
  "	Pustule	"	,
  "	Rabble-rouser	"	,
  "	rapscallion	"	,
  "	Refuse	"	,
  "	reprobate	"	,
  "	rogue	"	,
  "	Rot	"	,
  "	ruffian	"	,
  "	Vagabond	"	,
  "	Scab	"	,
  "	scoundrel	"	,
  "	simpleton	"	,
  "	Sinner	"	,
  "	Sod	"	,
  "	Sore	"	,
  "	Spigot	"	,
  "	Stain	"	,
  "	swindler	"	,
  "	Thumb sucker	"	,
  "	Toad	"	,
  "	tosspot	"	,
  "	trickster	"	,
  "	Troglodyte	"	,
  "	Troll	"	,
  "	Trollop	"	,
  "	Vermin	"	,
  "	villain	"	,
  "	Vole	"	,
  "	wastrel	"	,
  "	weasel	"	,
  "	worm	"	,
  "	wretch	" ,
  "	philistine	"	,
  "	vagabond	"	,
  "	rodent	"	,
  "	plebeian	" ,
  " fungus " ]

  const verbs = ["	Suffer	"	,
  "	Perish	"	,
  "	Be gone	"	,
  "	Quake	"	,
  "	Burst	"	,
  "	Break	"	,
  "	Crumble	"	,
  "	Despair	"	,
  "	Cry	"	,
  "	Weep	"	,
  "	Kneel	"	,
  "	I shall slash you	"	,
  "	I shall chop you	"	,
  "	I shall cut you	"	,
  "	I shall strike you down	"	,
  "	I shall beat you	"	,
  "	Stand aside	"	,
  "	Shove off	"	,
  "	Take heed	"	,
  "	Stop trying to hit me and hit me	"	,
  "	Tis but a scratch	"	,
  "	I laugh at thee	"	,
  "	I scoff at thee	"	,
  "	Have at thee	"	,
  "	I challenge thee	"	,
  "	Fight me	"	,
  "	Duel me	"	,
  "	Guard yourself	"	,
  "	Arm yourself	"	,
  "	Ready yourself	"	,
  "	Brace yourself	"	,
  "	En garde	"	,
  "	Hark	"	,
  "	Salutations	"	,
  "	Halt	"	,
  "	Stop right there	"	,
  "	Shove off	"	,
  "	Hello there	"	,
  "	Cower	"	,
  "	Fear me	"	,
  "	Fall	"	,
  "	Expire	"	,
  "	Tremble	"	,
  "	Shudder	"	,
  "	Shatter	"	,
  "	Splinter	"	,
  "	Sob	"	,
  "	Whimper	"	,
  "	Grieve	"	,
  "	Be slain	"	,
  "	Be struck	"	,
  "	Be thumped	"	,
  "	Be thrashed	"	,
  "	Be pummeled	"	,
  "	Be smacked	"	,
  "	Get thwacked	"	,
  "	Be routed	" ,
  " Get walloped " ,
  " Thou cannot escape " ,
  " Thou cannot flee " ,
  " Thou cannot run " ]

  let term1 = adjectives[Math.floor(Math.random()*adjectives.length)]
  let termsPost1 = adjectives.filter(term => term != term1)
  let term2 = termsPost1[Math.floor(Math.random()*termsPost1.length)]
  let term3 = nouns[Math.floor(Math.random()*nouns.length)]
  let term4 = verbs[Math.floor(Math.random()*verbs.length)]

  function refreshPage() {
    window.location.reload(false);
  }

  return (
    <><div className="Div1">
      <h2 className="Top-header">
        Throw the Gauntlet: 
      </h2>
      <button onClick={refreshPage} className="Button"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpFkMZMWYqbysCMPK7wfi47-dJej-ezArFaQ&usqp=CAU" alt="image of crossed swords" width="50" height="50"></img></button>
      </div>
      <div>
        <header className="Div2">
        <h1>
          {term4} , you {term1.toLowerCase()} {term2.toLowerCase()} {term3.toLowerCase()}!
        </h1>
        </header>
     </div>
    </>
  );
}

export default App;
